name: Build iOS Dylib

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build iOS Dylib
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install CMake
        run: brew install cmake

      - name: Configure CMake
        run: cmake -S . -B build -G Xcode

      - name: Build
        run: cmake --build build --config Release


      - name: Upload dylib
        uses: actions/upload-artifact@v3
        with:
          name: CharlieEngineInject.dylib
          path: /Users/runner/work/CharlieEngine/CharlieEngine/build/output/*.dylib
